-- NHT Operations Dashboard
-- Central Excel-data storage + atomic full refresh
-- Run this once in Supabase SQL Editor.
--
-- Purpose:
-- 1) Store processed Excel data centrally so users do NOT re-upload after every login.
-- 2) Keep one clean row per Month + Location.
-- 3) Exclude Excel summary/total rows before they reach the database.
-- 4) Let authenticated users read the shared dashboard.
-- 5) Let authenticated users update the dataset only through one controlled RPC.
-- 6) Keep a small upload history for traceability.

create table if not exists public.nht_dashboard_data (
  id bigint generated by default as identity primary key,
  month text not null,
  location text not null,
  batch numeric not null default 0,
  inflow numeric not null default 0,
  outflow numeric not null default 0,
  hr numeric not null default 0,
  training numeric not null default 0,
  throughput numeric not null default 0,
  joined numeric not null default 0,
  joining_throughput numeric not null default 0,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  constraint nht_dashboard_month_location_key unique (month, location)
);

create index if not exists nht_dashboard_month_idx
  on public.nht_dashboard_data (month);

create index if not exists nht_dashboard_location_idx
  on public.nht_dashboard_data (location);

create table if not exists public.nht_upload_history (
  id bigint generated by default as identity primary key,
  uploaded_at timestamptz not null default now(),
  uploaded_by uuid references auth.users(id),
  file_name text,
  records_loaded integer not null default 0
);

alter table public.nht_dashboard_data enable row level security;
alter table public.nht_upload_history enable row level security;

-- Remove broad direct-write access from the previous setup.
drop policy if exists "Authenticated users can read NHT data" on public.nht_dashboard_data;
drop policy if exists "Authenticated users can write NHT data" on public.nht_dashboard_data;

create policy "Authenticated users can read NHT data"
on public.nht_dashboard_data
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read upload history" on public.nht_upload_history;
create policy "Authenticated users can read upload history"
on public.nht_upload_history
for select
to authenticated
using (true);

-- Explicitly prevent normal browser clients from directly changing the table.
revoke insert, update, delete, truncate
on public.nht_dashboard_data
from authenticated, anon;

revoke insert, update, delete, truncate
on public.nht_upload_history
from authenticated, anon;

-- Controlled atomic refresh.
-- The browser sends only already-normalized location-level records.
-- If the RPC fails, the existing dashboard data is not intentionally replaced
-- by a partial client-side operation.
create or replace function public.replace_nht_dashboard_data(
  p_rows jsonb,
  p_file_name text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid;
  v_count integer;
begin
  v_user := auth.uid();

  if v_user is null then
    raise exception 'Authentication required';
  end if;

  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'p_rows must be a JSON array';
  end if;

  if jsonb_array_length(p_rows) = 0 then
    raise exception 'No NHT records supplied';
  end if;

  -- Validate required fields before changing the live dataset.
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as x(
      month text,
      location text,
      batch numeric,
      inflow numeric,
      outflow numeric,
      hr numeric,
      training numeric,
      throughput numeric,
      joined numeric,
      joining_throughput numeric
    )
    where nullif(trim(month), '') is null
       or nullif(trim(location), '') is null
  ) then
    raise exception 'Every NHT record must contain month and location';
  end if;

  -- Reject accidental summary rows such as "June Total".
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as x(
      month text,
      location text,
      batch numeric,
      inflow numeric,
      outflow numeric,
      hr numeric,
      training numeric,
      throughput numeric,
      joined numeric,
      joining_throughput numeric
    )
    where lower(trim(month)) ~ '(total|grand total|overall)$'
       or lower(trim(location)) ~ '(total|grand total|overall)$'
  ) then
    raise exception 'Summary/total rows are not allowed in the live dataset';
  end if;

  -- Reject duplicate Month + Location rows in the same upload.
  if exists (
    select 1
    from (
      select
        trim(x.month) as month,
        trim(x.location) as location,
        count(*) as c
      from jsonb_to_recordset(p_rows) as x(
        month text,
        location text,
        batch numeric,
        inflow numeric,
        outflow numeric,
        hr numeric,
        training numeric,
        throughput numeric,
        joined numeric,
        joining_throughput numeric
      )
      group by trim(x.month), trim(x.location)
      having count(*) > 1
    ) d
  ) then
    raise exception 'Duplicate Month + Location records found in upload';
  end if;

  -- Replace the complete dataset only after validation succeeds.
  delete from public.nht_dashboard_data;

  insert into public.nht_dashboard_data (
    month,
    location,
    batch,
    inflow,
    outflow,
    hr,
    training,
    throughput,
    joined,
    joining_throughput,
    updated_at,
    updated_by
  )
  select
    trim(x.month),
    trim(x.location),
    coalesce(x.batch, 0),
    coalesce(x.inflow, 0),
    coalesce(x.outflow, 0),
    coalesce(x.hr, 0),
    coalesce(x.training, 0),
    coalesce(x.throughput, 0),
    coalesce(x.joined, 0),
    coalesce(x.joining_throughput, 0),
    now(),
    v_user
  from jsonb_to_recordset(p_rows) as x(
    month text,
    location text,
    batch numeric,
    inflow numeric,
    outflow numeric,
    hr numeric,
    training numeric,
    throughput numeric,
    joined numeric,
    joining_throughput numeric
  );

  get diagnostics v_count = row_count;

  insert into public.nht_upload_history (
    uploaded_by,
    file_name,
    records_loaded
  )
  values (
    v_user,
    nullif(trim(p_file_name), ''),
    v_count
  );

  return v_count;
end;
$$;

grant execute on function public.replace_nht_dashboard_data(jsonb, text)
to authenticated;

revoke execute on function public.replace_nht_dashboard_data(jsonb, text)
from anon;

-- Remove the older one-argument signature if it exists, so the browser
-- cannot accidentally keep calling an obsolete implementation.
drop function if exists public.replace_nht_dashboard_data(jsonb);

-- Realtime: dashboard users can receive updates after an Excel refresh.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'nht_dashboard_data'
  ) then
    alter publication supabase_realtime
      add table public.nht_dashboard_data;
  end if;
end $$;

-- Optional verification queries:
-- select count(*) from public.nht_dashboard_data;
-- select * from public.nht_dashboard_data order by month, location;
-- select * from public.nht_upload_history order by uploaded_at desc;
