-- NHT Operations Dashboard V4 - one-time Supabase setup
create table if not exists public.nht_dashboard_data (
  id bigint generated by default as identity primary key,
  month text not null,
  location text not null,
  batch numeric not null default 0,
  inflow numeric not null default 0,
  outflow numeric not null default 0,
  hr numeric not null default 0,
  training numeric not null default 0,
  throughput numeric not null default 0,
  joined numeric not null default 0,
  joining_throughput numeric not null default 0,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique (month, location)
);

alter table public.nht_dashboard_data enable row level security;

drop policy if exists "Authenticated users can read NHT data" on public.nht_dashboard_data;
create policy "Authenticated users can read NHT data"
on public.nht_dashboard_data for select
to authenticated
using (true);

drop policy if exists "Authenticated users can write NHT data" on public.nht_dashboard_data;
create policy "Authenticated users can write NHT data"
on public.nht_dashboard_data for all
to authenticated
using (true)
with check (true);

create or replace function public.replace_nht_dashboard_data(p_rows jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  delete from public.nht_dashboard_data;

  insert into public.nht_dashboard_data
    (month, location, batch, inflow, outflow, hr, training, throughput, joined, joining_throughput, updated_at, updated_by)
  select
    x.month,
    x.location,
    coalesce(x.batch, 0),
    coalesce(x.inflow, 0),
    coalesce(x.outflow, 0),
    coalesce(x.hr, 0),
    coalesce(x.training, 0),
    coalesce(x.throughput, 0),
    coalesce(x.joined, 0),
    coalesce(x.joining_throughput, 0),
    now(),
    auth.uid()
  from jsonb_to_recordset(p_rows) as x(
    month text,
    location text,
    batch numeric,
    inflow numeric,
    outflow numeric,
    hr numeric,
    training numeric,
    throughput numeric,
    joined numeric,
    joining_throughput numeric
  );
end;
$$;

grant execute on function public.replace_nht_dashboard_data(jsonb) to authenticated;
revoke execute on function public.replace_nht_dashboard_data(jsonb) from anon;

-- Enable Supabase Realtime for live dashboard refreshes.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'nht_dashboard_data'
  ) then
    alter publication supabase_realtime add table public.nht_dashboard_data;
  end if;
end $$;
